name: C++ Build and Test with vcpkg

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git curl unzip

      - name: Remove existing vcpkg folder (if any)
        run: rm -rf vcpkg

      - name: Clone vcpkg fresh
        run: git clone https://github.com/microsoft/vcpkg.git

      - name: Clean vcpkg git repository to avoid baseline checkout errors
        run: |
          cd vcpkg
          git fetch --all
          git reset --hard origin/master
          git clean -fdx
          
      - name: Bootstrap vcpkg
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: Clear vcpkg installed cache (optional but safer)
        run: rm -rf vcpkg/installed

      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install vcpkg dependencies
        run: ./vcpkg/vcpkg install

      - name: Configure CMake with vcpkg toolchain
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
