name: C++ Build and Test with vcpkg

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git curl unzip

      - name: Clone and bootstrap vcpkg (full history)
        run: |
          rm -rf ./vcpkg
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          git fetch --unshallow || true
          ./bootstrap-vcpkg.sh

      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Install dependencies via vcpkg
        run: ./vcpkg/vcpkg install

      - name: Clean build directory
        run: |
            rm -rf build

      - name: Configure CMake with vcpkg toolchain
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build project
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
